services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file: .env
    volumes:
      - ./server/uploads:/app/uploads
      - ./server/output:/app/output
    restart: always

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: always

volumes:
  uploads:
  output: